tengined:
  daemon: true
  load_path: "/var/lib/tengine"
  pid_dir: "/var/run/tengined_pids"
  status_dir: "/var/run/tengined_status"
  activation_dir: "/var/run/tengined_activations"
event_queue:
  queue:
    name: tengine_event_queue2
