tengined:
  daemon: true
  load_path: "/var/lib/tengine/init.rb"
  log_dir: "/var/log/tengined"
  pid_dir: "/var/run/tengined_pids"
  activation_dir: "/var/run/tengined_activations"
event_queue:
  queue:
    name: tengine_event_queue2
